apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: serverless-operator
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  displayName: Serverless Operator
  image: image-registry.openshift-image-registry.svc:5000/openshift-marketplace/serverless-index:latest
  publisher: Red Hat
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: serverless
  namespace: openshift-serverless
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "serverless-operator"
  namespace: "openshift-serverless"
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: "stable"
  name: serverless-operator
  source: serverless-operator
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
