{
 "title": "Knative Eventing - Channel",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "eventNamespace",
    "label": "Namespace",
    "query": "label_values((kafkachannel_dispatcher_event_count{} OR inmemorychannel_dispatcher_event_count{}), namespace_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "In-Memory Channel Aggregated Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "In-Memory Channel: Event Count (rate per minute)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(inmemorychannel_dispatcher_event_count{namespace_name=\"$eventNamespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "In-Memory Channel: Success Rate (2xx Event, fraction rate per minute)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(inmemorychannel_dispatcher_event_count{namespace_name=\"$eventNamespace\", response_code_class=\"2xx\"}[1m])) / sum(rate(inmemorychannel_dispatcher_event_count{namespace_name=\"$eventNamespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "In-Memory Channel: Event Count by Event Type (rate per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(inmemorychannel_dispatcher_event_count{namespace_name=~\"$eventNamespace\"}[1m])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "In-Memory Channel: Event Count by Response Code Class (rate per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(inmemorychannel_dispatcher_event_count{namespace_name=\"$eventNamespace\"}[1m])) by (response_code_class)",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "In-Memory Channel: Failure Rate (non-2xx Event, fraction rate per minute)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(inmemorychannel_dispatcher_event_count{namespace_name=\"$eventNamespace\", response_code_class!=\"2xx\"}[1m])) / sum(rate(inmemorychannel_dispatcher_event_count{namespace_name=\"$eventNamespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "In-Memory Dispatcher: Event Dispatch Latency (ms)",
   "type": "graph",
   "description": "50th, 90th, 95th, 99th percentile of event dispatch latency over the last 1m",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(inmemorychannel_dispatcher_event_dispatch_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(inmemorychannel_dispatcher_event_dispatch_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kinmemorychannel_dispatcher_event_dispatch_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(inmemorychannel_dispatcher_event_dispatch_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Kafka Channel Aggregated Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Kafka Channel: Event Count (rate per minute)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kafkachannel_dispatcher_event_count{namespace_name=\"$eventNamespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Kafka Channel: Success Rate (2xx Event, fraction rate per minute)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kafkachannel_dispatcher_event_count{namespace_name=\"$eventNamespace\", response_code_class=\"2xx\"}[1m])) / sum(rate(kafkachannel_dispatcher_event_count{namespace_name=\"$eventNamespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Kafka Channel: Event Count by Event Type (rate per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafkachannel_dispatcher_event_count{namespace_name=~\"$eventNamespace\"}[1m])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Kafka Channel: Event Count by Response Code Class (rate per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafkachannel_dispatcher_event_count{namespace_name=\"$eventNamespace\"}[1m])) by (response_code_class)",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "Kafka Channel: Failure Rate (non-2xx Event, fraction rate per minute)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(kafkachannel_dispatcher_event_count{namespace_name=\"$eventNamespace\", response_code_class!=\"2xx\"}[1m])) / sum(rate(kafkachannel_dispatcher_event_count{namespace_name=\"$eventNamespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Kafka Dispatcher: Event Dispatch Latency (ms)",
   "type": "graph",
   "description": "50th, 90th, 95th, 99th percentile of event dispatch latency over the last 1m",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(kafkachannel_dispatcher_event_dispatch_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(kafkachannel_dispatcher_event_dispatch_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kafkachannel_dispatcher_event_dispatch_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kafkachannel_dispatcher_event_dispatch_latencies_bucket{namespace_name=~\"$eventNamespace\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}